# -*- mode: ruby -*-
# vi: set ft=ruby :

# Windows
# July 18, 2022

require_relative "../shared/shared.rb"

machines = {
    "windows-server-2022"   => {"box" => "gusztavvargadr/windows-server"                , "autostart" => false},
    "windows-server-2019"   => {"box" => "gusztavvargadr/windows-server-2019-standard"  , "autostart" => false},
    "windows-11"            => {"box" => "gusztavvargadr/windows-11"                    , "autostart" => false},
    "windows-10"            => {"box" => "gusztavvargadr/windows-10"                    , "autostart" => false},
}

Vagrant.configure("2") do |config|
    machines.each do |name, vm|
        config.vm.define name, autostart: vm["autostart"] do |v|
            v.vm.box = vm["box"]
            v.vm.hostname = name
            v.vm.network "private_network", ip: $hosts[name]
        end
    end

    # Windows-specific configurations
    config.vm.communicator = "winrm"
    config.winrm.port = 55985
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
    
    config.vm.provider "virtualbox" do |v|
        v.memory = $agentMemory
        v.cpus = $cpus
        v.gui = true
    end
end
